version: "3"

services:
  frontend:
    build:
      context: browser-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 8080:8080

  backend:
    build:
      context: api-backend
      dockerfile: Dockerfile
    ports:
      - 3333:3333
