version: "3"

services:
  frontend:
    build:
      context: browser-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 8080:8080
    volumes:
      - ./ssl:/etc/nginx/ssl

  backend:
    build:
      #      context: api-backend
      context: dotnet-backend
      dockerfile: Dockerfile
    environment:
      IMAGES_ROOT_DIR: /images
    ports:
      #      - 3333:3333
      - 3333:8080
    volumes:
      - ../stable-diffusion-webui-automatic1111/outputs:/images
      - ../comfy/ComfyUI/output:/images/comfyui
      - ../framepack/webui/outputs:/images/framepack

